export interface School {
  ko: string;
  en: string;
}

export const schools: School[] = [
  // === SKY + Top Tier ===
  { ko: '서울대학교', en: 'Seoul National University' },
  { ko: '한국과학기술원', en: 'KAIST' },
  { ko: '고려대학교', en: 'Korea University' },
  { ko: '연세대학교', en: 'Yonsei University' },
  { ko: '한양대학교', en: 'Hanyang University' },
  { ko: '중앙대학교', en: 'Chung-Ang University' },
  { ko: '포항공과대학교', en: 'POSTECH' },
  { ko: '경북대학교', en: 'Kyungpook National University' },
  { ko: '이화여자대학교', en: 'Ewha Womans University' },
  { ko: '경희대학교', en: 'Kyung Hee University' },
  { ko: '부산대학교', en: 'Pusan National University' },
  { ko: '서강대학교', en: 'Sogang University' },
  { ko: '성균관대학교', en: 'Sungkyunkwan University' },
  { ko: '세종대학교', en: 'Sejong University' },
  { ko: '한국외국어대학교', en: 'Hankuk University of Foreign Studies' },
  { ko: '강원대학교', en: 'Kangwon National University' },
  { ko: '서울시립대학교', en: 'University of Seoul' },
  { ko: '건국대학교', en: 'Konkuk University' },
  { ko: '단국대학교', en: 'Dankook University' },
  { ko: '울산과학기술원', en: 'UNIST' },
  { ko: '동국대학교', en: 'Dongguk University' },
  { ko: '숭실대학교', en: 'Soongsil University' },
  { ko: '국민대학교', en: 'Kookmin University' },
  { ko: '아주대학교', en: 'Ajou University' },
  { ko: '전남대학교', en: 'Chonnam National University' },
  { ko: '충남대학교', en: 'Chungnam National University' },
  { ko: '영남대학교', en: 'Yeungnam University' },
  { ko: '홍익대학교', en: 'Hongik University' },
  { ko: '부경대학교', en: 'Pukyong National University' },
  { ko: '가천대학교', en: 'Gachon University' },
  { ko: '명지대학교', en: 'Myongji University' },
  { ko: '전북대학교', en: 'Jeonbuk National University' },
  { ko: '숙명여자대학교', en: 'Sookmyung Women\'s University' },
  { ko: '경상국립대학교', en: 'Gyeongsang National University' },
  { ko: '인천대학교', en: 'University of Incheon' },
  { ko: '충북대학교', en: 'Chungbuk National University' },
  { ko: '인하대학교', en: 'Inha University' },
  { ko: '한림대학교', en: 'Hallym University' },
  { ko: '계명대학교', en: 'Keimyung University' },
  { ko: '공주대학교', en: 'Kongju National University' },
  { ko: '원광대학교', en: 'Wonkwang University' },
  { ko: '동아대학교', en: 'Dong-A University' },
  { ko: '광운대학교', en: 'Kwangwoon University' },
  { ko: '울산대학교', en: 'University of Ulsan' },
  { ko: '조선대학교', en: 'Chosun University' },
  { ko: '순천향대학교', en: 'Soonchunhyang University' },
  { ko: '서울과학기술대학교', en: 'Seoul National University of Science and Technology' },
  { ko: '가톨릭대학교', en: 'The Catholic University of Korea' },
  { ko: '한동대학교', en: 'Handong Global University' },
  { ko: '경기대학교', en: 'Kyonggi University' },
  { ko: '대구대학교', en: 'Daegu University' },
  { ko: '제주대학교', en: 'Jeju National University' },
  // === Mid Tier ===
  { ko: '창원대학교', en: 'Changwon National University' },
  { ko: '동서대학교', en: 'Dongseo University' },
  { ko: '상명대학교', en: 'Sangmyung University' },
  { ko: '호서대학교', en: 'Hoseo University' },
  { ko: '성신여자대학교', en: 'Sungshin University' },
  { ko: '한국기술교육대학교', en: 'Korea University of Technology and Education' },
  { ko: '선문대학교', en: 'Sun Moon University' },
  { ko: '인제대학교', en: 'Inje University' },
  { ko: '동의대학교', en: 'Dong-Eui University' },
  { ko: '대구가톨릭대학교', en: 'Catholic University of Daegu' },
  { ko: '경성대학교', en: 'Kyungsung University' },
  { ko: '한남대학교', en: 'Hannam University' },
  { ko: '광주대학교', en: 'Gwangju University' },
  { ko: '순천대학교', en: 'Sunchon National University' },
  { ko: '부산외국어대학교', en: 'Busan University of Foreign Studies' },
  { ko: '우송대학교', en: 'Woosong University' },
  { ko: '목포대학교', en: 'Mokpo National University' },
  { ko: '군산대학교', en: 'Kunsan National University' },
  { ko: '금오공과대학교', en: 'Kumoh National University of Technology' },
  { ko: '한국항공대학교', en: 'Korea Aerospace University' },
  { ko: '덕성여자대학교', en: 'Duksung Women\'s University' },
  { ko: '경남대학교', en: 'Kyungnam University' },
  { ko: '한성대학교', en: 'Hansung University' },
  { ko: '한국해양대학교', en: 'Korea Maritime and Ocean University' },
  { ko: '백석대학교', en: 'Baekseok University' },
  { ko: '한국예술종합학교', en: 'Korean National University of Arts' },
  { ko: '한밭대학교', en: 'Hanbat National University' },
  { ko: '전주대학교', en: 'Jeonju University' },
  { ko: '한국교통대학교', en: 'Korea National University of Transportation' },
  { ko: '신라대학교', en: 'Silla University' },
  { ko: '삼육대학교', en: 'Sahmyook University' },
  { ko: '장로회신학대학교', en: 'Presbyterian University and Theological Seminary' },
  { ko: '동신대학교', en: 'Dongshin University' },
  { ko: '청주대학교', en: 'Cheongju University' },
  { ko: '한국공학대학교', en: 'Tech University of Korea' },
  { ko: '강남대학교', en: 'Kangnam University' },
  { ko: '대진대학교', en: 'Daejin University' },
  { ko: '수원대학교', en: 'The University of Suwon' },
  { ko: '배재대학교', en: 'Pai Chai University' },
  { ko: '한국교원대학교', en: 'Korea National University of Education' },
  { ko: '과학기술연합대학원대학교', en: 'University of Science and Technology Korea' },
  { ko: '강릉원주대학교', en: 'Gangneung-Wonju National University' },
  { ko: '고신대학교', en: 'Kosin University' },
  { ko: '건양대학교', en: 'Konyang University' },
  { ko: '우석대학교', en: 'Woosuk University' },
  { ko: '한서대학교', en: 'Hanseo University' },
  { ko: '세명대학교', en: 'Semyung University' },
  { ko: '서울여자대학교', en: 'Seoul Women\'s University' },
  { ko: '총신대학교', en: 'Chongshin University' },
  { ko: '안양대학교', en: 'Anyang University' },
  { ko: '대구한의대학교', en: 'Daegu Haany University' },
  { ko: '서경대학교', en: 'Seokyeong University' },
  { ko: '경극대학교', en: 'Kyungkuk National University' },
  { ko: '영산대학교', en: 'Youngsan University' },
  { ko: '대전대학교', en: 'Daejeon University' },
  // === More ===
  { ko: '동양대학교', en: 'Dongyang University' },
  { ko: '목원대학교', en: 'Mokwon University' },
  { ko: '가톨릭관동대학교', en: 'Catholic Kwandong University' },
  { ko: '동명대학교', en: 'Tongmyung University' },
  { ko: '동덕여자대학교', en: 'Dongduk Women\'s University' },
  { ko: '세한대학교', en: 'Sehan University' },
  { ko: '서원대학교', en: 'Seowon University' },
  { ko: '중부대학교', en: 'Joongbu University' },
  { ko: '성공회대학교', en: 'Sungkonghoe University' },
  { ko: '한경대학교', en: 'Hankyong National University' },
  { ko: '차의과대학교', en: 'CHA University' },
  { ko: '상지대학교', en: 'Sangji University' },
  { ko: '호남대학교', en: 'Honam University' },
  { ko: '을지대학교', en: 'Eulji University' },
  { ko: '나사렛대학교', en: 'Korea Nazarene University' },
  { ko: '한신대학교', en: 'Hanshin University' },
  { ko: '경일대학교', en: 'Kyungil University' },
  { ko: '평택대학교', en: 'Pyeongtaek University' },
  { ko: '용인대학교', en: 'Yong-In University' },
  { ko: '성결대학교', en: 'Sungkyul University' },
  { ko: '서울교육대학교', en: 'Seoul National University of Education' },
  { ko: '남서울대학교', en: 'Namseoul University' },
  { ko: '초당대학교', en: 'Chodang University' },
  { ko: '서울신학대학교', en: 'Seoul Theological University' },
  { ko: '한국체육대학교', en: 'Korea National Sport University' },
  { ko: '남부대학교', en: 'Nambu University' },
  { ko: '목포해양대학교', en: 'Mokpo National Maritime University' },
  { ko: '경인교육대학교', en: 'Gyeongin National University of Education' },
  { ko: '경동대학교', en: 'Kyungdong University' },
  { ko: '부산교육대학교', en: 'Busan National University of Education' },
  { ko: '경운대학교', en: 'Kyungwoon University' },
  { ko: '위덕대학교', en: 'Uiduk University' },
  { ko: '협성대학교', en: 'Hyupsung University' },
  { ko: '대구교육대학교', en: 'Daegu National University of Education' },
  { ko: '호원대학교', en: 'Howon University' },
  { ko: '강서대학교', en: 'Gangseo University' },
  { ko: '김천대학교', en: 'Gimcheon University' },
  { ko: '가야대학교', en: 'Kaya University' },
  { ko: '한세대학교', en: 'Hansei University' },
  { ko: '청운대학교', en: 'Chungwoon University' },
  { ko: '부산가톨릭대학교', en: 'Catholic University of Pusan' },
  { ko: '침례신학대학교', en: 'Korea Baptist Theological University' },
  { ko: '한라대학교', en: 'Halla University' },
  { ko: '추계예술대학교', en: 'Chugye University for the Arts' },
  { ko: '극동대학교', en: 'Far East University' },
  { ko: '공주교육대학교', en: 'Gongju National University of Education' },
  { ko: '청주교육대학교', en: 'Cheongju National University of Education' },
  { ko: '광주교육대학교', en: 'Gwangju National University of Education' },
  { ko: '광주여자대학교', en: 'Kwangju Women\'s University' },
  { ko: '진주교육대학교', en: 'Chinju National University of Education' },
  { ko: '금강대학교', en: 'Geumgang University' },
  { ko: '유원대학교', en: 'U1 University' },
  { ko: '성경대학교', en: 'Korean Bible University' },
  { ko: '예원예술대학교', en: 'Yewon Arts University' },
  { ko: '가톨릭꽃동네대학교', en: 'Catholic Kkottongnae University' },
  { ko: '춘천교육대학교', en: 'Chuncheon National University of Education' },
  { ko: '중원대학교', en: 'Jungwon University' },
  { ko: '대신대학교', en: 'Daeshin University' },
  { ko: '전주교육대학교', en: 'Jeonju National University of Education' },
  { ko: '인천가톨릭대학교', en: 'Incheon Catholic University' },
  { ko: '대전가톨릭대학교', en: 'Catholic University of Daejeon' },
  { ko: '서울장신대학교', en: 'Seoul Jangsin University' },
  { ko: '제주국제대학교', en: 'Jeju International University' },
  { ko: '서울기독대학교', en: 'Seoul Christian University' },
  { ko: '부산장신대학교', en: 'Busan Presbyterian University' },
  { ko: '광주가톨릭대학교', en: 'Gwangju Catholic University' },
  { ko: '대구예술대학교', en: 'Daegu Arts University' },
  // === Language Schools (Popular with international students) ===
  { ko: '연세대학교 한국어학당', en: 'Yonsei KLI (Korean Language Institute)' },
  { ko: '고려대학교 한국어센터', en: 'Korea University Korean Language Center' },
  { ko: '서울대학교 언어교육원', en: 'Seoul National University Language Education Institute' },
  { ko: '경희대학교 국제교육원', en: 'Kyung Hee University Institute of International Education' },
  { ko: '한양대학교 국제어학원', en: 'Hanyang University International Language Institute' },
  { ko: '성균관대학교 성균어학원', en: 'SKKU Sungkyun Language Institute' },
];
